plugins {
	id 'java'
	id 'org.springframework.boot' version "${springBootVersion}"
	id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
	id 'pmd'
	id 'org.openapi.generator' version "${openapiGeneratorVersion}"
	id 'io.freefair.lombok' version "${lombokVersion}"
}

group = 'fit.man'
version = '1.0.0'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of("${javaVersion}")
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-liquibase'

	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocStarterUi}"

	implementation "org.mapstruct:mapstruct:${mapstructVersion}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

	implementation "com.garmin:fit:${fitVersion}"

	runtimeOnly 'org.postgresql:postgresql'

//	testImplementation 'org.springframework.boot:spring-boot-starter-thymeleaf-test'
//	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

pmd {
	consoleOutput = true
	version = "${pmdVersion}"
	rulesMinimumPriority = 5
	ruleSets = []
	ruleSetFiles = files("$rootDir/pmd/ruleset.xml")
}

openApiGenerate {
	generatorName = "spring"
	inputSpec = "$rootDir/api/openapi-fit-man.yaml"
	outputDir = "$rootDir/build/generated/openapi"
	apiPackage = "fit.man.app.api"
	modelPackage = "fit.man.app.api.model"
	validateSpec = true
	importMappings = [
			"Nullable": "org.jspecify.annotations.Nullable"
	]
	configOptions = [
	        "useSpringBoot4": "true",
			"useJackson3": "true",
			"openApiNullable": "false",
			"generateBuilders": "true",
			"interfaceOnly": "true",
			"useSpringNullSafety": "false",
			"additionalModelTypeAnnotations": "@org.jspecify.annotations.NullMarked"
	]
}

sourceSets {
	main {
		java {
			srcDirs += "$rootDir/build/generated/openapi/src/main/java"
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
