org.gradle.configuration-cache=true

# plugins
javaVersion=25
springBootVersion=4.0.5
springDependencyManagementVersion=1.1.7
pmdVersion=7.23.0
openapiGeneratorVersion=7.21.0
lombokVersion=9.2.0

# dependencies
springdocStarterUi=3.0.2
mapstructVersion=1.6.3
fitVersion=21.195.0
h2databaseVersion=2.4.240

# paths
rulesetFile=/pmd/ruleset.xml
apiSpecDir=/api
apiGenDir=/build/generated/openapi