spring:
  application:
    name: app
  threads:
    virtual:
      enabled: true
  liquibase:
    change-log: db/changelog/changelog.yaml
    enabled: true
    drop-first: false
  datasource:
    url: jdbc:postgresql://localhost:5432/fit-man-db?reWriteBatchedInserts=true
    username: fit-man
    password: fit-man
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true
springdoc:
  swagger-ui:
    api-docs:
      enabled: false
    url: /openapi-fit-man.yaml
    syntaxHighlight:
      activated: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) --- [%magenta(%thread)] %cyan(%logger{20}) : %.-500m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
fit-man:
  activity-scheduler:
    fixed-rate: PT1M
    batch-size: 1
    max-speed: 60 # km/h